/**
 * Parses PixelCode TTF (v2.2) and outputs a C header with bitmap font data.
 *
 * Usage:
 *   bun scripts/gen_pixelcode_font.ts [path/to/PixelCode.ttf]
 *
 * If no path is given, downloads the TTF from GitHub automatically.
 */
import opentype from "opentype.js";
import { existsSync } from "fs";

const UNITS_PER_PIXEL = 112;
const GLYPH_WIDTH = 6;   // pixels (advance width 672 / 112)
const Y_MIN = -112;       // lowest pixel row (descenders)
const Y_MAX = 896;         // highest pixel row
const GLYPH_HEIGHT = (Y_MAX - Y_MIN) / UNITS_PER_PIXEL; // 10

/** Test if point is inside a set of contours using even-odd rule (ray cast). */
function pointInPath(px: number, py: number, contours: { x: number; y: number }[][]): boolean {
  let inside = false;
  for (const contour of contours) {
    for (let i = 0, j = contour.length - 1; i < contour.length; j = i++) {
      const xi = contour[i].x, yi = contour[i].y;
      const xj = contour[j].x, yj = contour[j].y;
      if ((yi > py) !== (yj > py) && px < ((xj - xi) * (py - yi)) / (yj - yi) + xi) {
        inside = !inside;
      }
    }
  }
  return inside;
}

/** Extract contours (arrays of vertices) from an opentype glyph path. */
function getContours(glyph: opentype.Glyph): { x: number; y: number }[][] {
  const contours: { x: number; y: number }[][] = [];
  let current: { x: number; y: number }[] = [];
  for (const cmd of glyph.path.commands) {
    if (cmd.type === "M") {
      current = [{ x: cmd.x, y: cmd.y }];
    } else if (cmd.type === "L") {
      current.push({ x: cmd.x, y: cmd.y });
    } else if (cmd.type === "Z") {
      if (current.length) contours.push(current);
      current = [];
    }
  }
  return contours;
}

/** Rasterize a glyph to a GLYPH_WIDTH x GLYPH_HEIGHT bitmap. */
function rasterize(glyph: opentype.Glyph): number[][] {
  const contours = getContours(glyph);
  const rows: number[][] = [];

  // Row 0 = top of cell (Y_MAX), row last = bottom (Y_MIN)
  for (let row = 0; row < GLYPH_HEIGHT; row++) {
    const py = Y_MAX - row * UNITS_PER_PIXEL - UNITS_PER_PIXEL / 2;
    const bits: number[] = [];
    for (let col = 0; col < GLYPH_WIDTH; col++) {
      const px = col * UNITS_PER_PIXEL + UNITS_PER_PIXEL / 2;
      bits.push(pointInPath(px, py, contours) ? 1 : 0);
    }
    rows.push(bits);
  }
  return rows;
}

/** Convert a row of pixel bits to a byte (LSB = leftmost pixel, matching font8x8). */
function rowToByte(bits: number[]): number {
  let byte = 0;
  for (let i = 0; i < bits.length; i++) {
    if (bits[i]) byte |= 1 << i;
  }
  return byte;
}

async function getFontPath(): Promise<string> {
  const arg = process.argv[2];
  if (arg && existsSync(arg)) return arg;

  // Download from GitHub
  const tmpPath = "/tmp/pixelcode_gen/PixelCode.ttf";
  if (existsSync(tmpPath)) return tmpPath;

  console.error("Downloading PixelCode v2.2 from GitHub...");
  const { mkdirSync } = await import("fs");
  mkdirSync("/tmp/pixelcode_gen", { recursive: true });

  const proc = Bun.spawnSync([
    "gh", "release", "download", "v2.2",
    "--repo", "qwerasd205/PixelCode",
    "--pattern", "ttf.zip",
    "--dir", "/tmp/pixelcode_gen",
  ]);
  if (proc.exitCode !== 0) {
    throw new Error("Failed to download: " + proc.stderr.toString());
  }
  Bun.spawnSync(["unzip", "-o", "/tmp/pixelcode_gen/ttf.zip", "-d", "/tmp/pixelcode_gen"]);
  const { copyFileSync } = await import("fs");
  copyFileSync("/tmp/pixelcode_gen/ttf/PixelCode.ttf", tmpPath);
  return tmpPath;
}

// --- Main ---

const fontPath = await getFontPath();
const font = opentype.loadSync(fontPath);

const lines: string[] = [];
lines.push(`/**`);
lines.push(` * PixelCode font v2.2 - ${GLYPH_WIDTH}x${GLYPH_HEIGHT} monochrome bitmap`);
lines.push(` * Source: https://github.com/qwerasd205/PixelCode`);
lines.push(` * License: OFL-1.1`);
lines.push(` *`);
lines.push(` * Auto-generated by scripts/gen_pixelcode_font.ts`);
lines.push(` */`);
lines.push(``);
lines.push(`#pragma once`);
lines.push(``);
lines.push(`#define PIXELCODE_FONT_WIDTH  ${GLYPH_WIDTH}`);
lines.push(`#define PIXELCODE_FONT_HEIGHT ${GLYPH_HEIGHT}`);
lines.push(``);
lines.push(`unsigned char font_pixelcode[128][${GLYPH_HEIGHT}] = {`);

for (let code = 0; code < 128; code++) {
  let bytes: number[];
  if (code < 0x20 || code === 0x7f) {
    // Zero out control characters (matching font8x8_basic convention)
    bytes = new Array(GLYPH_HEIGHT).fill(0);
  } else {
    const ch = String.fromCharCode(code);
    const glyph = font.charToGlyph(ch);
    const bitmap = rasterize(glyph);
    bytes = bitmap.map(rowToByte);
  }
  const hex = bytes.map((b) => `0x${b.toString(16).toUpperCase().padStart(2, "0")}`).join(", ");

  const ch = String.fromCharCode(code);
  let comment: string;
  if (code < 0x20) {
    comment = `U+${code.toString(16).toUpperCase().padStart(4, "0")}`;
  } else if (code === 0x7f) {
    comment = `U+007F (DEL)`;
  } else {
    comment = `U+${code.toString(16).toUpperCase().padStart(4, "0")} (${ch === "\\" ? "\\\\" : ch === '"' ? '\\"' : ch})`;
  }

  const comma = code < 127 ? "," : " ";
  lines.push(`    { ${hex} }${comma}  // ${comment}`);
}

lines.push(`};`);
lines.push(``);

const output = lines.join("\n");
const outPath = "src/fonts/font_pixelcode.h";
await Bun.write(outPath, output);
console.log(`Wrote ${outPath}`);

// Print a visual preview of a few characters
for (const ch of ["A", "B", "g", "@", "0"]) {
  const glyph = font.charToGlyph(ch);
  const bitmap = rasterize(glyph);
  console.log(`\n'${ch}':`);
  for (const row of bitmap) {
    console.log("  " + row.map((b) => (b ? "#" : ".")).join(""));
  }
}
