#pragma once

#include "base/base_inc.h"

typedef enum {
  TOKEN_UNKNOWN,

  TOKEN_IDENTIFIER,
  TOKEN_INT_LITERAL,
  TOKEN_FLOAT_LITERAL,
  TOKEN_STRING_LITERAL,
  TOKEN_CHAR_LITERAL,

  TOKEN_COMMENT_LINE,
  TOKEN_COMMENT_BLOCK,
  TOKEN_PREPROCESSOR,

  TOKEN_PLUS,
  TOKEN_PLUS_PLUS,
  TOKEN_MINUS,
  TOKEN_MINUS_MINUS,
  TOKEN_STAR,
  TOKEN_DIVIDE,
  TOKEN_PERCENT,

  TOKEN_EQ,
  TOKEN_EQ_EQ,
  TOKEN_BANG,
  TOKEN_BANG_EQ,

  TOKEN_LT,
  TOKEN_LT_EQ,
  TOKEN_GT,
  TOKEN_GT_EQ,

  TOKEN_AND,
  TOKEN_AND_AND,
  TOKEN_OR,
  TOKEN_OR_OR,
  TOKEN_CARET,
  TOKEN_TILDE,
  TOKEN_QUESTION,

  TOKEN_LPAREN,
  TOKEN_RPAREN,
  TOKEN_LBRACE,
  TOKEN_RBRACE,
  TOKEN_LBRACKET,
  TOKEN_RBRACKET,

  TOKEN_COMMA,
  TOKEN_SEMICOLON,
  TOKEN_COLON,
  TOKEN_DOT,
  TOKEN_ARROW,

  TOKEN_KEYWORD_RETURN,
  TOKEN_KEYWORD_IF,
  TOKEN_KEYWORD_ELSE,
  TOKEN_KEYWORD_WHILE,
  TOKEN_KEYWORD_FOR,
  TOKEN_KEYWORD_DO,
  TOKEN_KEYWORD_SWITCH,
  TOKEN_KEYWORD_CASE,
  TOKEN_KEYWORD_DEFAULT,
  TOKEN_KEYWORD_BREAK,
  TOKEN_KEYWORD_CONTINUE,
  TOKEN_KEYWORD_GOTO,
  TOKEN_KEYWORD_SIZEOF,
  TOKEN_KEYWORD_STATIC,
  TOKEN_KEYWORD_CONST,
  TOKEN_KEYWORD_EXTERN,
  TOKEN_KEYWORD_TYPEDEF,
  TOKEN_KEYWORD_STRUCT,
  TOKEN_KEYWORD_ENUM,
  TOKEN_KEYWORD_UNION,
  TOKEN_KEYWORD_VOLATILE,
  TOKEN_KEYWORD_INLINE,
  TOKEN_KEYWORD_REGISTER,

  TOKEN_TYPE_INT,
  TOKEN_TYPE_FLOAT,
  TOKEN_TYPE_CHAR,
  TOKEN_TYPE_VOID,
  TOKEN_TYPE_SHORT,
  TOKEN_TYPE_LONG,
  TOKEN_TYPE_SIGNED,
  TOKEN_TYPE_UNSIGNED,
  TOKEN_TYPE_DOUBLE,
  TOKEN_TYPE_BOOL,
  TOKEN_TYPE_BUILTIN,

  TOKEN_CONST_TRUE,
  TOKEN_CONST_FALSE,
  TOKEN_CONST_NULL,

  TOKEN_COUNT,
} TokenType;

typedef struct {
  size_t start;
  size_t end;
} Span;

typedef struct {
  TokenType type;
  Span span;
} Token;

typedef struct {
  Token *tokens;
  size_t count;
} TokenizeResult;

TokenizeResult tokenize(Arena *arena, s8 source);
